Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -113,58 +113,58 @@ jobs:
         distribution: 'temurin'
         java-version: '21'
 
-    - name: Debug - Verificar Secreto APP_KEYSTORE_BASE64
-      run: |
-        if [ -z "${{ secrets.APP_KEYSTORE_BASE64 }}" ]; then
-          echo "Error: El secreto APP_KEYSTORE_BASE64 está vacío."
-          exit 1
-        else
-          echo "El secreto APP_KEYSTORE_BASE64 está presente. (Solo se muestran los primeros 20 caracteres para depuración)"
-          echo "${{ secrets.APP_KEYSTORE_BASE64 }}" | head -c 20
-        fi
-    
-    - name: Decode Keystore
-      uses: timheuer/base64-to-file@v1.2.4
-      id: android_keystore
-      with:
-        fileName: "android_keystore.jks"
-        encodedString: ${{ secrets.APP_KEYSTORE_BASE64 }}
-    
-    - name: Build APK
-      run: |
-        cd ${{ github.workspace }}/V2rayNG
-        echo "sdk.dir=${ANDROID_HOME}" > local.properties
-        chmod 755 gradlew
-        ./gradlew licenseFdroidReleaseReport
-        ./gradlew assembleRelease -Pandroid.injected.signing.store.file=${{ steps.android_keystore.outputs.filePath }} -Pandroid.injected.signing.store.password=${{ secrets.APP_KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.APP_KEYSTORE_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.APP_KEY_PASSWORD }}
-    
-    - name: Upload arm64-v8a APK
-      uses: actions/upload-artifact@v4.6.2
-      if: ${{ success() }}
-      with:
-        name: arm64-v8a
-        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/*/release/*arm64-v8a*.apk
-    
-    - name: Upload armeabi-v7a APK
-      uses: actions/upload-artifact@v4.6.2
-      if: ${{ success() }}
-      with:
-        name: armeabi-v7a
-        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/*/release/*armeabi-v7a*.apk
-    
-    - name: Upload x86 APK
-      uses: actions/upload-artifact@v4.6.2
-      if: ${{ success() }}
-      with:
-        name: x86-apk
-        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/*/release/*x86*.apk
-    
-    - name: Upload to release
-      uses: svenstaro/upload-release-action@v2
-      if: github.event.inputs.release_tag != ''
-      with:
-        file: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/*playstore*/release/*.apk
-        tag: ${{ github.event.inputs.release_tag }}
-        file_glob: true
-        prerelease: true
+  - name: Debug - Verificar Secreto UPLOAD_KEYSTORE_BASE64
+    run: |
+      if [ -z "${{ secrets.UPLOAD_KEYSTORE_BASE64 }}" ]; then
+        echo "Error: El secreto UPLOAD_KEYSTORE_BASE64 está vacío."
+        exit 1
+      else
+        echo "El secreto UPLOAD_KEYSTORE_BASE64 está presente. (Solo se muestran los primeros 20 caracteres para depuración)"
+        echo "${{ secrets.UPLOAD_KEYSTORE_BASE64 }}" | head -c 20
+      fi
+  
+  - name: Decode Keystore
+    uses: timheuer/base64-to-file@v1.2.4
+    id: android_keystore
+    with:
+      fileName: "android_keystore.jks"
+      encodedString: ${{ secrets.UPLOAD_KEYSTORE_BASE64 }}
+  
+  - name: Build APK
+    run: |
+      cd ${{ github.workspace }}/V2rayNG
+      echo "sdk.dir=${ANDROID_HOME}" > local.properties
+      chmod 755 gradlew
+      ./gradlew licenseFdroidReleaseReport
+      ./gradlew assembleRelease -Pandroid.injected.signing.store.file=${{ steps.android_keystore.outputs.filePath }} -Pandroid.injected.signing.store.password=${{ secrets.UPLOAD_KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.APP_KEYSTORE_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.APP_KEY_PASSWORD }}
+  
+  - name: Upload arm64-v8a APK
+    uses: actions/upload-artifact@v4.6.2
+    if: ${{ success() }}
+    with:
+      name: arm64-v8a
+      path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/*/release/*arm64-v8a*.apk
+  
+  - name: Upload armeabi-v7a APK
+    uses: actions/upload-artifact@v4.6.2
+    if: ${{ success() }}
+    with:
+      name: armeabi-v7a
+      path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/*/release/*armeabi-v7a*.apk
+  
+  - name: Upload x86 APK
+    uses: actions/upload-artifact@v4.6.2
+    if: ${{ success() }}
+    with:
+      name: x86-apk
+      path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/*/release/*x86*.apk
+  
+  - name: Upload to release
+    uses: svenstaro/upload-release-action@v2
+    if: github.event.inputs.release_tag != ''
+    with:
+      file: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/*playstore*/release/*.apk
+      tag: ${{ github.event.inputs.release_tag }}
+      file_glob: true
+      prerelease: true
 
